#!/bin/bash

pip install -r requirements.txt

mkdir -p ~/.local/bin/ && cp -r tracehost ~/.local/bin/tracehost
chmod +x ~/.local/bin/tracehost

if ! grep -q "alias trace='sudo python3 ~/.local/bin/trace'" ~/.bashrc; then
    echo "alias trace='sudo python3 ~/.local/bin/trace'" >> ~/.bashrc
    source ~/.bashrc
fi

source ~/.bashrc
