#!/bin/bash

mkdir -p ~/.local/bin/tracehost && cp tracehost ~/.local/bin/tracehost
chmod +x ~/.local/bin/tracehost
echo "alias tracehost='sudo python3 ~/.local/bin/tracehost'" >> ~/.bashrc
source ~/.bashrc
